config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # resources :dogs, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :dogs do
    collection do
      get  'purchase/:id'=>  'dogs#purchase', as: 'purchase'
      get  'done'=>      'dogs#done', as: 'done'
    end
  end

  resources :keep, only: [:index]

end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    {id: 1, name: '3ヶ月以下'},
    {id: 2, name: '3ヶ月以上、6ヶ月以下'},
    {id: 3, name: '6ヶ月以上、1年以下'},
    {id: 4, name: '1歳'},
    {id: 5, name: '2歳'},
    {id: 6, name: '3歳'},
    {id: 7, name: '4歳'},
    {id: 8, name: '5歳'},
    {id: 9, name: '6歳以上'}
  ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    {id: 1, name: '良好'},
    {id: 2, name: 'ちょっと調子悪い'}
  ]
end

app/models/dog.rb
class Dog < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  has_many :images
  accepts_nested_attributes_for :images, allow_destroy: true

  belongs_to_active_hash :dog_breed
  belongs_to_active_hash :age
  belongs_to_active_hash :sex
  belongs_to_active_hash :condition

  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true

  validates  :images, presence: true
  validates  :name, presence: true, uniqueness: { case_sensitive: true }, length: {maximum: 10}
  validates  :introduction, presence: true, uniqueness: { case_sensitive: true }, length: {minimum: 10}

  validates  :dog_breed_id,
             :age_id,
             :sex_id,
             :condition_id,
             presence: true
  

  enum status: {
    "募集中": 1,
    "里親見つかりました": 2
  }
end

app/models/dog_breed.rb
class DogBreed < ActiveHash::Base
  self.data = [
    {id: 0, name: '雑種'},
    {id: 1, name: '柴犬'},
    {id: 2, name: '土佐犬'},
    {id: 3, name: '秋田県'},
    {id: 4, name: '紀州犬'},
    {id: 5, name: '甲斐犬'},
    {id: 6, name: '四国県'},
    {id: 7, name: '北海道犬'},
    {id: 8, name: '屋久島犬'},
    {id: 9, name: '川上犬'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :dog
end

app/models/keep.rb
class Keep < ApplicationRecord
end

app/models/sex.rb
class Sex < ActiveHash::Base
  self.data = [
    {id: 1, name: '雄'},
    {id: 2, name: '雌'},
    {id: 3, name: '不明'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, length: {maximum: 6 }
  validates :first_name, presence: true, format: {
    with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/,
    message: "は全角入力をお願いします"
  }
  validates :family_name, presence: true, format: {
    with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/,
    message: "は全角入力をお願いします"
  }
  validates :first_name_kana, presence: true, format: {
    with: /\A[\p{katakana}\p{blank}ー－]+\z/,
    message: 'は全角カナで入力して下さい。'
   }
  validates :family_name_kana, presence: true, format: {
    with: /\A[\p{katakana}\p{blank}ー－]+\z/,
    message: 'は全角カナで入力して下さい。'
    }


  validates :phone, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:index, :show]
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,
      :first_name,
      :family_name,
      :first_name_kana,
      :family_name_kana,
      :phone
      ])
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy, :purchase]

  def index
    @dogs = Dog.includes(:image).order('created_at DESC')
  end

  def new
    @dog = Dog.new
    @dog.images.new
  end

  def create
    @dog = Dog.new(dog_params)
    if 
      @dog.valid?
      @dog.save
      redirect_to root_path
    else
      @dog.images.new
      render :new
    end
  end

  def show
    # @dog = Dog.find(params[:id])
    @images = @dog.images
  end

  def edit
    @dog.images.build
    # @dog.images.cache! unless @dog.images.blank?
  end

  def update
    if @dog.update(dog_params)
      redirect_to dog_path
      # @dog.update(status: "里親見つかりました")
    else
      redirect_to edit__path
    end
  end

  def destroy
    @dog.destroy
  end

  def purchase
    @dog_buyer = @dog
    @dog_buyer.update( buyer_id: current_user.id)
    @dog.update(status: "里親見つかりました")
  end

  def done
  end

  private
  def dog_params
    params.require(:dog).permit(
      :name,
      :introduction,
      :dog_breed_id,
      :age_id,
      :sex_id,
      :condition_id,
      images_attributes: [:src, :id, :_destroy,]).merge(seller_id: current_user.id)

  end

  def set_dog
    @dog = Dog.find(params[:id])
  end
  #     使うならbefore_actionを定義する
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @dogs = Dog.all.order(created_at: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/_details.html.haml
.basics
  .basics__frame
    .basics__frame__box
      .basics__frame__box__title
        %h3 詳細ページ

    .image__Box
      .image__Box__main
        = image_tag @images.first.src.url, {class: 'q'}
      .image__Box__sub
        - @images.each do |image|
          = image_tag image.src.url, {class: 'w'}

    .introduction__box
      .introduction__box__name
        %h3 紹介文
      .introduction__box__comment
        = @dog.introduction

    .table
      %table
        %tbody
          %tr
            %th 名前
            %td
              = @dog.name

          %tr
            %th 種類
            %td
              = @dog.dog_breed.name

          %tr
            %th 年齢
            %td
              = @dog.age.name

          %tr
            %th 性別
            %td
              = @dog.sex.name

          %tr
            %th 健康状態
            %td
              = @dog.condition.name
  .basics__frame
    .basics__frame__link
      .basics__frame__link__box
        - if user_signed_in? && current_user.id == @dog.seller_id
          = link_to "削除する", dog_path(@dog.id), method: :delete,class:"aaa"
          = link_to "編集する", edit_dog_path(@dog.id), method: :get,class:"aaa"
        - elsif @dog.buyer_id.present?
          = link_to "里親見つかりました", root_path, class:"aaa"
        - else
          = link_to "引き取りページに進む",purchase_dogs_path(@dog),class:"aaa"

    .comment__box
      %text_area

    .comment__box__note
      %p
        不快なコメントは退会処分になる事があります。

app/views/dogs/_form.html.haml
.container
  -# 画像タイトル
  = form_with model: @dog, local: true do |f|
    .container__content
      .a
        .container__content__photo
          %h3.phototitle__text
            Dog photo
          %p.phototitle__comment
            最大4枚までアップロード
            #image-Input__label
              %i.fa.fa-camera
                カメラをクリックしてアップロード

        -# 画像入る場所
        .photobox
          .outputBox
            .image_box#preview
              - if @dog.persisted?
                - @dog.images.each_with_index do |image, i|
                  - if image.persisted?
                    .new_image_wrapper#mini{data: {index: i}}
                      = image_tag image.src.url,data: { index: i }, width: "200", height: '200'
                      .js-remove
                        削除する
              %div#imageInput
                = f.fields_for :images do |image|
                  = image.file_field :src, accept: "image/*", class: "js-file", data:{index: image.index}, style: 'display: none;'
                  - if image.object.persisted?
                    = image.check_box :_destroy, include_hidden: false, class: 'hidden-destroy'

        .messages__dog
          = @dog.errors.full_messages_for(:images)[0]
    -# 説明
    .a
      .container__Content
        .container__content__title
          %h3.dog__text
            紹介
          = f.text_area :introduction, class: "introduction__form", maxlength: "1000", placeholder:"1000字まで"
        .messages__dog
          = @dog.errors.full_messages_for(:introduction)[0]

    -# 名前
    .container__contents
      .container__contents__title
        %h3.dog__text
          名前
        = f.text_field :name, class: "dog__form", maxlength: "10", placeholder:"10字まで"
        .messages__dog
          = @dog.errors.full_messages_for(:name)[0]

    -# 犬種
    .container__contents
      .container__contents__title
        %h3.dog__text
          種類
        = f.collection_select :dog_breed_id, DogBreed.all, :id, :name, {prompt: "選択してください"}, {class: "dog__form"}
        .messages__dog
          = @dog.errors.full_messages_for(:dog_breed_id)[0]

    -# 年齢
    .container__contents
      .container__contents__title
        %h3.dog__text
          年齢
        = f.collection_select :age_id, Age.all, :id, :name, {prompt: "選択してください"}, {class: "dog__form"}
        .messages__dog
          = @dog.errors.full_messages_for(:age_id)[0]

    -# 性別
    .container__contents
      .container__contents__title
        %h3.dog__text
          性別
        = f.collection_select :sex_id, Sex.all, :id, :name, {prompt: "選択してください"}, {class: "dog__form"}
        .messages__dog
          = @dog.errors.full_messages_for(:sex_id)[0]

    -# 健康状態
    .container__contents
      .container__contents__title
        %h3.dog__text
          健康状態
        = f.collection_select :condition_id, Condition.all, :id, :name, {prompt: "選択してください"}, {class: "dog__form"}
        .messages__dog
          = @dog.errors.full_messages_for(:condition_id)[0]

    -# 登録ボタン
    .container__content
      .container__content__btn
        = f.submit "登録", class: "dog__btn"

app/views/dogs/destroy.html.haml
.main
  .main__content
    .main__content__itembox
      %h3.main__content__itembox__name
        削除が完了しました
      .main__content__itembox_retarn_btn
        = link_to 'もどる', root_path, class: "main__content__itembox__comment__btn"

app/views/dogs/done.html.haml
.done
  .done__box
    .done__heading
      .done__heading__text
        里親になりました。
      .done__heading__text
        = link_to "トップページへ戻る", root_path, class: "purchase__dicision__btn"

app/views/dogs/edit.html.haml
= render partial: 'form'

app/views/dogs/new.html.haml
= render partial: 'form'

app/views/dogs/purchase.html.haml
.main
  %section.main__block
    .header
      .header__logo
        -# =link_to image_tag('logo.png',class: "header__logo__image"), root_path
  .purchase
    .purchase__box
      .purchase__heading
        .purchase__heading__text
          内容の確認
      %hr
      .purchase__dog
        .purchase__dog__photo
          = image_tag "#{@dog.images[0].src}", size: '64x64', class: 'buydetails-contet__image'
        .purchase__dog__info
          .name
            = @dog.name

        .purchase__dicision
          -# %button.purchase__dicision__btn{type:"submit"} 里親になる
          = link_to "里親になる",done_dogs_path,class:"purchase__dicision__btn"
          = link_to "トップページへ戻る", root_path, class: "purchase__dicision__btn"

        -# .purchase__shipping__name
        -#   = @user.family_name
        -#   = @user.first_name

app/views/dogs/show.html.haml
= render partial: 'details'

app/views/homes/index.html.haml
.top
  .top__image
    = link_to image_tag("fd91d63fa421d122a857dcf597553e80.jpg", class: "top__image", alt: "イメージ画像")
.boxList
  最新の募集
.dogListBox
  .dogLists
    - @dogs.each.with_index(1) do |dog, x|
      - if x <= 5
        .dogList
          = link_to dog_path(dog) do
            %figure.dogList--img
              = image_tag "#{dog.images[0].src}"
                -if dog.buyer_id.present? 
                .itemsBoxPhotoSolid
                  .itemsBoxPhotoSolid__inner Found
            .dogList--body
              %h3.name
                = dog.name 

app/views/layouts/_error_messages.html.haml
-# -if model.errors.any?
-#   .alert
-#     %ul
-#       -model.errors.full_messages.each do |message|
-#         %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Onedog

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'

  %body
    .pcHeader
      = render "shared/header"
    = yield
    .footer
      = render "shared/footer"

app/views/shared/_footer.html.haml
%ul.contents
  %li.content
    %h2.content__head One dogについて
    %ul
      %li
        = link_to "#" do
          会社概要（運営会社）
      %li
        = link_to "#" do
          プライバシーポリシー
      %li
        = link_to "#" do
          利用規約

  %li.content
    %h2.content__head ヘルプ＆ガイド
    %ul
      %li
        = link_to "#" do
          One dogガイド
      %li
        = link_to "#" do
          お知らせ

app/views/shared/_header.html.haml
.main
  .main__header
    .main__header__left
      .main__header__left__box
        %h2.main__header__left__box__title
          = link_to "OneDog", root_path, class: "ondog__title"
        %h3.main__header__left__box__text

    .main__header__center
      .main__header__center__box
        .main__header__center__box__text


    .main__header__right
      .main__header__right__box
        %ul.main__header__right__box__list
          - if user_signed_in?
            %li.main__header__right__box__list__link
              -# = link_to "マイページ",
              = link_to "ログアウト",destroy_user_session_path, method: :delete, class: "main__header__left__box__text__btn" 
            %li.main__header__right__box__list__link
              = link_to "里親募集Link", new_dog_path, class: "main__header__left__box__text__btn"
          - else
            %li.main__header__right__box__list__link
              = link_to "ログイン", new_user_session_path, class: "main__header__left__box__text__btn"
            %li.main__header__right__box__list__link
              = link_to "新規登録", new_user_registration_path, class: "main__header__left__box__text__btn"